version: '3'
services:
  jekyll:
      image: jekyll/builder:latest
      # (for --config) settings in later files override settings in earlier files
      command: |
              bundle exec jekyll serve \
                --watch \
                --incremental \
                --config _config.yml,_config-dev.yml \
                --host 0.0.0.0
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll:cached
          - ./vendor/bundle:/usr/local/bundle:cached
