version: '3'
services:
  jekyll:
      image: jekyll/builder:latest
      environment:
        - JEKYLL_ENV=development
      command: bundle exec jekyll serve --watch --incremental --config _config-dev.yml --host 0.0.0.0
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll:cached
          # - ./vendor/bundle:/usr/local/bundle:cached
