version: '3'
services:
  jekyll:
      image: jekyll/jekyll:latest
      # (for --config) settings in later files override settings in earlier files
      command:  bash -c "
                  bundle install ;
                  bundle exec jekyll serve
                    --watch
                    --incremental
                    --config _config.yml,_config-dev.yml"
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll:cached
